const TIMESHEET_STATUS_APPROVED = "Approved";
const TIMESHEET_STATUS_WAITING = "Waiting";
const TIMESHEET_STATUS_REJECTED = "Rejected";
const TIMESHEET_STATUS_LIST = [
  TIMESHEET_STATUS_APPROVED,
  TIMESHEET_STATUS_REJECTED,
  TIMESHEET_STATUS_WAITING,
];

export {
  TIMESHEET_STATUS_APPROVED,
  TIMESHEET_STATUS_LIST,
  TIMESHEET_STATUS_REJECTED,
  TIMESHEET_STATUS_WAITING,
};
